Repository kunaldhongade/CPP-hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#11 Create queue.cpp
  queue.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#9 Circular Linked List with operations of Add, Delete and Display all t…
  extra/Circular Linked List.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#14 added new cpp solution
  bs-sol.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#18 fixes no #17
  bs-sol.cpp
  queue.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#19 HELLO
  Assignment 1/setA/2calculactor.cpp
  Assignment 2/setA/que1.cpp
  HELLO.CPP
  README.md
Labels: hacktoberfest-accepted, HACKTOBERFEST

#29 Calulator in C++
  Cpp/C++/Calculator.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#30 Contributed 30+ CPP codes specially for beginners
  Cpp/C++/Beginners Problems/AggresiveCows.cpp
  Cpp/C++/Beginners Problems/AllocateBook.cpp
  Cpp/C++/Beginners Problems/ClimbStairs.cpp
  Cpp/C++/Beginners Problems/CountElements.cpp
  Cpp/C++/Beginners Problems/CountPrime.cpp
  Cpp/C++/Beginners Problems/DuplicatesInArray.cpp
  Cpp/C++/Beginners Problems/ExactSquareRoot.cpp
  Cpp/C++/Beginners Problems/FindDuplicate.cpp
  Cpp/C++/Beginners Problems/FindUnique.cpp
  Cpp/C++/Beginners Problems/FirstAndLastPosition.cpp
  Cpp/C++/Beginners Problems/IntersectionInArray.cpp
  Cpp/C++/Beginners Problems/MergeSortedArray.cpp
  Cpp/C++/Beginners Problems/ModularExponentiation.cpp
  Cpp/C++/Beginners Problems/MoveZeroes.cpp
  Cpp/C++/Beginners Problems/PaintersPartition.cpp
  Cpp/C++/Beginners Problems/PairSum.cpp
  Cpp/C++/Beginners Problems/ReverseArray.cpp
  Cpp/C++/Beginners Problems/SayDigits.cpp
  Cpp/C++/Beginners Problems/SetBit.cpp
  Cpp/C++/Beginners Problems/SquareRoot.cpp
  Cpp/C++/Beginners Problems/SumOfTwoArrays.cpp
  Cpp/C++/Beginners Problems/SwapAlternate.cpp
  Cpp/C++/Beginners Problems/TripletSum.cpp
  Cpp/C++/Beginners Problems/UniqueAccurance.cpp
  Cpp/C++/Beginners Problems/calculator.c
  Cpp/C++/Beginners Problems/fibonacciNumber.cpp
  Cpp/C++/Beginners Problems/gcd.cpp
  Cpp/C++/Beginners Problems/nCr.cpp
  Cpp/C++/Beginners Problems/sort.cpp
  Cpp/C++/Beginners Problems/sort01.cpp
  Cpp/C++/Beginners Problems/sort012.cpp
  Cpp/Searching Algorithms/BinarySearch.cpp
  Cpp/Searching Algorithms/LinearSearch.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#31 Create Celebrity_Problem.cpp
  Cpp/Celebrity_Problem.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#42 Create DFSgraph.cpp
  DFSgraph.cpp
Labels: hacktoberfest-accepted, HACKTOBERFEST

#48 Added interpolation_sort.cpp
  Cpp/Searching Algorithms/Interpolation_Search.cpp
Labels: good first issue, hacktoberfest-accepted

#47 Added Shell sort in c++
  Cpp/Sorting_Algorithms/ShellSort.cpp
Labels: good first issue, hacktoberfest-accepted

#52 Create GnomeSort.cpp
  Cpp/Sorting_Algorithms/GnomeSort.cpp
Labels: hacktoberfest-accepted

#51 Create BitonicSort.cpp
  Cpp/Sorting_Algorithms/BitonicSort.cpp
Labels: hacktoberfest-accepted

#50 Create CombSort.cpp
  Cpp/Sorting_Algorithms/CombSort.cpp
Labels: hacktoberfest-accepted

#49 Create PigeonHoleSort.cpp
  Cpp/Sorting_Algorithms/PigeonHoleSort.cpp
Labels: hacktoberfest-accepted
